INSERT INTO problem_category (problem_category_id, problem_category_name, created_at, updated_at)
VALUES
    (1, 'Breadth-First Search', NOW(), NOW()),
    (2, 'Depth-First Search', NOW(), NOW()),
    (3, 'Graph', NOW(), NOW()),
    (4, 'Dynamic Programming', NOW(), NOW()),
    (5, 'Array', NOW(), NOW()),
    (6, 'Stack', NOW(), NOW()),
    (7, 'Queue', NOW(), NOW()),
    (8, 'Union Find', NOW(), NOW()),
    (9, 'Backtracking', NOW(), NOW()),
    (10, 'Recursion', NOW(), NOW()),
    (11, 'Binary Search', NOW(), NOW()),
    (12, 'Sorting', NOW(), NOW()),
    (13, 'Greedy', NOW(), NOW()),
    (14, 'Two Pointers', NOW(), NOW()),
    (15, 'Bit Manipulation', NOW(), NOW()),
    (16, 'Hashing', NOW(), NOW()),
    (17, 'Sliding Window', NOW(), NOW()),
    (18, 'Math', NOW(), NOW()),
    (19, 'String', NOW(), NOW()),
    (20, 'Tree', NOW(), NOW()),
    (21, 'Binary Indexed Tree', NOW(), NOW()),
    (22, 'Binary Search Tree', NOW(), NOW()),
    (23, 'Binary Tree', NOW(), NOW()),
    (24, 'Bitmask', NOW(), NOW()),
    (25, 'Brainteaser', NOW(), NOW()),
    (26, 'Bucket Sort', NOW(), NOW()),
    (27, 'Combinatorics', NOW(), NOW()),
    (28, 'Counting', NOW(), NOW()),
    (29, 'Counting Sort', NOW(), NOW()),
    (30, 'Divide and Conquer', NOW(), NOW()),
    (31, 'Enumeration', NOW(), NOW()),
    (32, 'Eulerian Circuit', NOW(), NOW()),
    (33, 'Game Theory', NOW(), NOW()),
    (34, 'Geometry', NOW(), NOW()),
    (35, 'Hash Function', NOW(), NOW()),
    (36, 'Hash Table', NOW(), NOW()),
    (37, 'Heap (Priority Queue)', NOW(), NOW()),
    (38, 'Interactive', NOW(), NOW()),
    (39, 'Line Sweep', NOW(), NOW()),
    (40, 'Linked List', NOW(), NOW()),
    (41, 'Matrix', NOW(), NOW()),
    (42, 'Memoization', NOW(), NOW()),
    (43, 'Merge Sort', NOW(), NOW()),
    (44, 'Monotonic Queue', NOW(), NOW()),
    (45, 'Monotonic Stack', NOW(), NOW()),
    (46, 'Number Theory', NOW(), NOW()),
    (47, 'Ordered Set', NOW(), NOW()),
    (48, 'Prefix Sum', NOW(), NOW()),
    (49, 'Quickselect', NOW(), NOW()),
    (50, 'Radix Sort', NOW(), NOW()),
    (51, 'Rolling Hash', NOW(), NOW()),
    (52, 'Segment Tree', NOW(), NOW()),
    (53, 'Simulation', NOW(), NOW()),
    (54, 'String Matching', NOW(), NOW()),
    (55, 'Topological Sort', NOW(), NOW()),
    (56, 'Trie', NOW(), NOW());